name: Test My Action

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: poutine - GitHub Actions SAST
        uses: boostsecurityio/poutine-action@v0.15.2
      
      - name: Run my custom action
        id: action
        uses: ./.github/actions/my-action
        with:
          input-name: 'Hello World'
      
      - name: Use output
        run: echo "Output was:${{ steps.action.outputs.output-name }}"